### ISSUE TITLE
Add the accordion `type` prop to the component interface

### ISSUE THREAD

**Issue by andrewreifman** [makeswift/vibes#204]
https://github.com/makeswift/vibes/blob/63934d11e79ebf9bf69473835ce07315a246938d/apps/web/vibes/soul/components/accordions/index.tsx#L13

**Comment by Samantha2233** [comment]
Resolved in: https://github.com/makeswift/vibes/pull/227/commits/1630b968f04df51e4f1f2893936880670a6fcfb6
