### ISSUE TITLE
Numeric values should be written as numbers instead of strings

### ISSUE THREAD

**Issue by andrewreifman** [makeswift/vibes#205]
https://github.com/makeswift/vibes/blob/63934d11e79ebf9bf69473835ce07315a246938d/apps/web/vibes/soul/components/accordions/index.tsx#L66-L86

**Comment by Samantha2233** [comment]
Resolved in: https://github.com/makeswift/vibes/pull/227/commits/a75eaecdcc63f8fcc9cf092f89b63f737e3fa436
