### ISSUE TITLE
Avoid using header block tags in accordion trigger

### ISSUE THREAD

**Issue by andrewreifman** [makeswift/vibes#207]
https://github.com/makeswift/vibes/blob/63934d11e79ebf9bf69473835ce07315a246938d/apps/web/vibes/soul/components/accordions/index.tsx#L38

Since we don't know if these should always be <h3> blocks, should we just avoid using them and just use <div>?

**Comment by Samantha2233** [comment]
@andrewreifman Would you recommend using a `span` instead? Or did you have something else in mind?
