### ISSUE TITLE
Outlines should only apply when using `focus-visible`

### ISSUE THREAD

**Issue by andrewreifman** [makeswift/vibes#213]
https://github.com/makeswift/vibes/blob/63934d11e79ebf9bf69473835ce07315a246938d/apps/web/vibes/soul/components/card/index.tsx#L28

This is a personal preference, but I think that focus outlines should only appear when using keyboard actions like TAB. For example in the card carousel, it feels weird to show outlines when I click and drag the carousel.

This pattern should be applied to all components.

**Comment by Samantha2233** [comment]
Resolved in: https://github.com/makeswift/vibes/pull/227/commits/1a88aac8a94b4d771326b2157a3cda54d3dc69d6
