### ISSUE TITLE
Apply styles directly to `<textarea>`

### ISSUE THREAD

**Issue by andrewreifman** [makeswift/vibes#214]
https://github.com/makeswift/vibes/blob/63934d11e79ebf9bf69473835ce07315a246938d/apps/web/vibes/soul/components/textarea/index.tsx#L26

Can we not remove this wrapper and just apply the styles directly to the `<textarea>`?

**Comment by Samantha2233** [comment]
The textarea component has been refactored and this issue seems to be resolved 👍
